name: MiAlcaldia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"
# Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.2
    flutter_rating_bar: ^4.0.1
    
    animations: ^2.0.3
    
    get:
    firebase_database: ^4.4.0
    firebase_storage: ^5.2.0
    table_calendar: ^3.0.3
    google_maps_flutter: ^2.0.6
    audioplayer: ^0.8.1
    google_fonts: ^1.1.2
    syncfusion_flutter_datepicker: ^20.4.42
    logger: ^1.1.0
    colombia_holidays: ^2.0.2
    flutter_localizations:
        sdk: flutter
    shared_preferences: ^2.0.15
    
    
    
    
    

dev_dependencies:
    flutter_test:
        sdk: flutter


dependency_overrides:
    google_sign_in: ^4.5.5
    firebase_auth: ^0.18.2
    flutter_signin_button: ^1.1.0
    flutter_screenutil: ^5.6.0
    intl: ^0.17.0
    date_format: ^1.0.6
    day_night_time_picker: ^1.1.4
    image_picker: ^0.5.0+3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/
        - assets/images/
        - assets/diseño_interfaz/
        - assets/image_01.png
        - assets/image_02.png
        - assets/logoo.png
        - assets/MiMunicipio.mp3

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400

        - family: CustomIcons
          fonts:
              - asset: assets/CustomIcons.ttf

        - family: Poppins-Bold
          fonts:
              - asset: assets/Poppins-Bold.ttf
        

        - family: Poppins-Medium
          fonts:
              - asset: assets/Poppins-Medium.ttf   
    
        - family: ITCEDSCR
          fonts:
              - asset: assets/ITCEDSCR.ttf 
    
        - family: BERNHC
          fonts:
              - asset: assets/BERNHC.ttf 

    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
