// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcSM8R1EdslDP09P979U-juuwkZpyIxdM',
    appId: '1:746363711706:web:690d0213fbac80a02f75e3',
    messagingSenderId: '746363711706',
    projectId: 'alcaldia-para-todos',
    authDomain: 'alcaldia-para-todos.firebaseapp.com',
    databaseURL: 'https://alcaldia-para-todos-default-rtdb.firebaseio.com',
    storageBucket: 'alcaldia-para-todos.appspot.com',
    measurementId: 'G-LQW3VKZV0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABRJP2wBeIpEWC3tzpEug9rC2-F_BC_6E',
    appId: '1:746363711706:android:4ea9123a0053900b2f75e3',
    messagingSenderId: '746363711706',
    projectId: 'alcaldia-para-todos',
    databaseURL: 'https://alcaldia-para-todos-default-rtdb.firebaseio.com',
    storageBucket: 'alcaldia-para-todos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALA5aAEkFfCpdQv70Dt4CeQK55xKBIx1s',
    appId: '1:746363711706:ios:b9d93c365a8cb08e2f75e3',
    messagingSenderId: '746363711706',
    projectId: 'alcaldia-para-todos',
    databaseURL: 'https://alcaldia-para-todos-default-rtdb.firebaseio.com',
    storageBucket: 'alcaldia-para-todos.appspot.com',
    androidClientId: '746363711706-docbbffdava55vj4a2cu8l7qld9g8210.apps.googleusercontent.com',
    iosClientId: '746363711706-3k419stbpts410om7sba6qeh2mgh616b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );
}
